# revision identifiers, used by Alembic.
revision = '26dfc22ea16e'
down_revision = '4e33b96ffceb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('airport', sa.Integer(), nullable=True))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'airport')

